version: "3.8"

services:
  minecraft:
    container_name: minecraft
    image: itzg/minecraft-server:java8-multiarch
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: "1.16.5"
      MODS_FILE: /extras/mods.txt
      REMOVE_OLD_MODS: "true"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./minecraft-data:/data
      - ./mods.txt:/extras/mods.txt:ro
volumes:
  data:
